name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  docker-login:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      run: docker login -u realneeleshsharma -p docker@555
    
  docker-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker push
      run: docker push my-image-name:$(date +%s)
